openapi: 3.0.0
info:
  title: Habit Tracker API
  version: 1.0.0
  description: API for tracking habits and tasks

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  # Auth

  /auth/register:
    post:
      $ref: "./auth/endpoints.yaml#/register"

  /auth/login:
    post:
      $ref: "./auth/endpoints.yaml#/login"

  /auth/refresh:
    post:
      $ref: "./auth/endpoints.yaml#/refresh"

  /auth/logout:
    post:
      $ref: "./auth/endpoints.yaml#/logout"
  
  #Projects

  # /projects:
  #   get:
  #     $ref: "./projects/endpoints.yaml#/getAllProjects"
  #   post:
  #     $ref: "./projects/endpoints.yaml#/createProject"

  # /projects/{projectId}:
  #   delete:
  #     $ref: "./projects/endpoints.yaml#/deleteProjectById"
  
  # /projects/{projectId}/tasks:
  #   get:
  #     $ref: "./projects/endpoints.yaml#/getTasksByProject"
  #   post:
  #     $ref: "./projects/endpoints.yaml#/createTask"
  
  # /projects/{projectId}/tasks/{taskId}:
  #   delete:
  #     $ref: "./projects/endpoints.yaml#/deleteTask"
